### ISSUE TITLE
`lastElementChild` cause collapsing in IE8

### ISSUE THREAD

**Issue by ganlanyuan** [Alhadis/Fix-IE#1]
`lastElementChild` cause collapsing in IE8.  
Other element-related properties like `firstElementChild`, `previousElementSibling` don't have this issue.  
![ie8](https://cloud.githubusercontent.com/assets/4998811/13809323/a704b5b8-eb40-11e5-8362-5f1240201296.png)

My markup is like this:

``` html
<h2></h2>
<p></p>
<ul class="parent-element">
  <li></li>
  <li></li>
  <li></li>
</ul>
<p></p>
<p class="parent-element-output output"></p>
```

CSS:

``` css
.parent-element .first { background: #FF66FF; }
.parent-element .last { background: #FF8000; }
p.prev { background: #66CCFF; }
p.next { background: #804000; }
```

JS:

``` javascript
var 
    parentEl = d.querySelector('.parent-element'),
    parentElO = d.querySelector('.parent-element-output'),
    childCount = parentEl.childElementCount,
    firstChild = parentEl.firstElementChild,
    lastChild = parentEl.lastElementChild,
    prevEl = parentEl.previousElementSibling,
    nextEl = parentEl.nextElementSibling;
firstChild.classList.add('first');
lastChild.classList.add('last');
prevEl.classList.add('prev');
nextEl.classList.add('next');
parentElO.textContent = "childElementCount: " + childCount;
```
